#!/usr/bin/env zsh

branch=$1

if [[ ! -n $branch ]]; then
  echo 'usage: git wipe-branch [branch]'
  return 1
fi

git branch -d $branch
git branch -rd "origin/$branch"
git push origin :$branch

return 0
